
server:
  port: 8080
spring:
  profiles:
    active: b1

---
server:
  port: 8081
spring:
  profiles: dev
---

server:
  port: 8082
spring:
  profiles: b1

---
server:
  port: 8083
spring:
  profiles: at