server:
  port: 8082

student:
  name: zhangsan
  age: 24
  gender: 男

config-attributes:
  value: "this is a \n string value"                           #对应单个值
  valueArray: 1,2,3,4,5,6,7,8,9      #对应数组
  valueList:                         #对应list
    - 13579
    - 246810
  valueMap:                          #对应map<String, String>
    name: lili
    age: 20
    sex: female
  valueMapList:                      #对应list<map<String, String>>
    - name: bob
      age: 21
    - name: caven
      age: 31